RegistroEventos/Controllers/CapituloesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RegistroEventos.Data;
using RegistroEventos.Models;

namespace RegistroEventos.Controllers
{
    public class CapituloesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CapituloesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Capituloes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.capitulos.Include(c => c.Tipo_capitulo);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Capituloes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var capitulo = await _context.capitulos
                .Include(c => c.Tipo_capitulo)
                .FirstOrDefaultAsync(m => m.id_capitulo == id);
            if (capitulo == null)
            {
                return NotFound();
            }

            return View(capitulo);
        }

        // GET: Capituloes/Create
        public IActionResult Create()
        {
            ViewData["id_tipo_capitulo"] = new SelectList(_context.tipo_Capitulos, "id_tipo_capitulo", "nombre_tipo_capitulo");
            return View();
        }

        // POST: Capituloes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_capitulo,nombre_capitulo,lugar_capitulo,id_tipo_capitulo")] Capitulo capitulo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(capitulo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_tipo_capitulo"] = new SelectList(_context.tipo_Capitulos, "id_tipo_capitulo", "nombre_tipo_capitulo", capitulo.id_tipo_capitulo);
            return View(capitulo);
        }

        // GET: Capituloes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var capitulo = await _context.capitulos.FindAsync(id);
            if (capitulo == null)
            {
                return NotFound();
            }
            ViewData["id_tipo_capitulo"] = new SelectList(_context.tipo_Capitulos, "id_tipo_capitulo", "nombre_tipo_capitulo", capitulo.id_tipo_capitulo);
            return View(capitulo);
        }

        // POST: Capituloes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_capitulo,nombre_capitulo,lugar_capitulo,id_tipo_capitulo")] Capitulo capitulo)
        {
            if (id != capitulo.id_capitulo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(capitulo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CapituloExists(capitulo.id_capitulo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_tipo_capitulo"] = new SelectList(_context.tipo_Capitulos, "id_tipo_capitulo", "nombre_tipo_capitulo", capitulo.id_tipo_capitulo);
            return View(capitulo);
        }

        // GET: Capituloes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var capitulo = await _context.capitulos
                .Include(c => c.Tipo_capitulo)
                .FirstOrDefaultAsync(m => m.id_capitulo == id);
            if (capitulo == null)
            {
                return NotFound();
            }

            return View(capitulo);
        }

        // POST: Capituloes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var capitulo = await _context.capitulos.FindAsync(id);
            _context.capitulos.Remove(capitulo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CapituloExists(int id)
        {
            return _context.capitulos.Any(e => e.id_capitulo == id);
        }
    }
}

RegistroEventos/Controllers/Tipo_capituloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RegistroEventos.Data;
using RegistroEventos.Models;

namespace RegistroEventos.Controllers
{
    public class Tipo_capituloController : Controller
    {
        private readonly ApplicationDbContext _context;

        public Tipo_capituloController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tipo_capitulo
        public async Task<IActionResult> Index()
        {
            return View(await _context.tipo_Capitulos.ToListAsync());
        }

        // GET: Tipo_capitulo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipo_capitulo = await _context.tipo_Capitulos
                .FirstOrDefaultAsync(m => m.id_tipo_capitulo == id);
            if (tipo_capitulo == null)
            {
                return NotFound();
            }

            return View(tipo_capitulo);
        }

        // GET: Tipo_capitulo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tipo_capitulo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_tipo_capitulo,nombre_tipo_capitulo")] Tipo_capitulo tipo_capitulo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipo_capitulo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipo_capitulo);
        }

        // GET: Tipo_capitulo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipo_capitulo = await _context.tipo_Capitulos.FindAsync(id);
            if (tipo_capitulo == null)
            {
                return NotFound();
            }
            return View(tipo_capitulo);
        }

        // POST: Tipo_capitulo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id_tipo_capitulo,nombre_tipo_capitulo")] Tipo_capitulo tipo_capitulo)
        {
            if (id != tipo_capitulo.id_tipo_capitulo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipo_capitulo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Tipo_capituloExists(tipo_capitulo.id_tipo_capitulo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipo_capitulo);
        }

        // GET: Tipo_capitulo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipo_capitulo = await _context.tipo_Capitulos
                .FirstOrDefaultAsync(m => m.id_tipo_capitulo == id);
            if (tipo_capitulo == null)
            {
                return NotFound();
            }

            return View(tipo_capitulo);
        }

        // POST: Tipo_capitulo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tipo_capitulo = await _context.tipo_Capitulos.FindAsync(id);
            _context.tipo_Capitulos.Remove(tipo_capitulo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Tipo_capituloExists(int id)
        {
            return _context.tipo_Capitulos.Any(e => e.id_tipo_capitulo == id);
        }
    }
}

RegistroEventos/Views/Capituloes/Create.cshtml
@model RegistroEventos.Models.Capitulo

@{
    ViewData["Title"] = "Crear-Capítulo";
}

<link rel="stylesheet" href="~/css/Style-crud.css" />
<link rel="stylesheet" href="~/img/fihnec-logo.png" />
<h4 class="txt-h4">Registrar Participante</h4>

<img id="logo-participantes" src="~/img/fihnec-logo.png"/>


    <div class="cont-add-parti">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group p1">
                <label asp-for="nombre_capitulo" class="control-label"></label>
                <input asp-for="nombre_capitulo" placeholder="Ingrese nombre del capítulo" class="form-control" />
                <span asp-validation-for="nombre_capitulo" class="text-danger"></span>
            </div>
            <div class="form-group p2">
                <label asp-for="lugar_capitulo" class="control-label"></label>
                <input asp-for="lugar_capitulo" placeholder="Ingrese el lugar del capítulo" class="form-control" />
                <span asp-validation-for="lugar_capitulo" class="text-danger"></span>
            </div>
            <div class="form-group p3">
                <label asp-for="id_tipo_capitulo" class="control-label"></label>
                <select asp-for="id_tipo_capitulo" class ="form-control" asp-items="ViewBag.id_tipo_capitulo"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-outline-dark boton-guardar" />
                 <a class="btn btn-outline-dark boton-cancelar" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RegistroEventos/Views/Capituloes/Delete.cshtml
@model RegistroEventos.Models.Capitulo

@{
    ViewData["Title"] = "Eliminar-Capítulo";
}
<link rel="stylesheet" href="~/css/Style-crud.css" />
<link rel="stylesheet" href="~/img/fihnec-logo.png" />
<h4 class="txt-h4">Eliminar Participante</h4>

<img id="logo-participantes" src="~/img/fihnec-logo.png"/>
<div class="cont-add-parti">
    
    <dl class="row Style-delete">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre_capitulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre_capitulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lugar_capitulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lugar_capitulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo_capitulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo_capitulo.nombre_tipo_capitulo)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
         <input type="hidden" asp-for="id_capitulo" />
        <input type="submit" value="Eliminar" class="btn btn-outline-dark boton-cancelar" />
        <a class="btn btn-outline-dark boton-guardar" asp-action="Index">Cancelar</a>
    </form>
</div>

RegistroEventos/Views/Capituloes/Details.cshtml
@model RegistroEventos.Models.Capitulo

@{
    ViewData["Title"] = "Detalle-Capítulo";
}

<link rel="stylesheet" href="~/css/Style-crud.css" />
<link rel="stylesheet" href="~/img/fihnec-logo.png" />
<h4 class="txt-h4">Detalle Participante</h4>

<img id="logo-participantes" src="~/img/fihnec-logo.png"/>

<div class"cont-add-parti">
    
    <dl class="row Style-delete">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre_capitulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre_capitulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lugar_capitulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lugar_capitulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo_capitulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo_capitulo.nombre_tipo_capitulo)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-dark boton-cancelar-detalle" asp-action="Index">Cancelar</a>
</div>

RegistroEventos/Views/Capituloes/Edit.cshtml
@model RegistroEventos.Models.Capitulo

@{
    ViewData["Title"] = "Editar-Capítulo";
}

<link rel="stylesheet" href="~/css/Style-crud.css" />
<link rel="stylesheet" href="~/img/fihnec-logo.png" />
<h4 class="txt-h4">Editar Capítulo</h4>

<img id="logo-participantes" src="~/img/fihnec-logo.png"/>

    <div class="cont-add-parti">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id_capitulo" />
            <div class="form-group p1">
                <label asp-for="nombre_capitulo" class="control-label"></label>
                <input asp-for="nombre_capitulo" class="form-control" />
                <span asp-validation-for="nombre_capitulo" class="text-danger"></span>
            </div>
            <div class="form-group p2">
                <label asp-for="lugar_capitulo" class="control-label"></label>
                <input asp-for="lugar_capitulo" class="form-control" />
                <span asp-validation-for="lugar_capitulo" class="text-danger"></span>
            </div>
            <div class="form-group p3">
                <label asp-for="id_tipo_capitulo" class="control-label"></label>
                <select asp-for="id_tipo_capitulo" class="form-control" asp-items="ViewBag.id_tipo_capitulo"></select>
                <span asp-validation-for="id_tipo_capitulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-outline-dark boton-guardar" />
                 <a class="btn btn-outline-dark boton-cancelar" asp-action="Index">Cancelar</a>
            </div>
        </form>
    </div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RegistroEventos/Views/Capituloes/Index.cshtml
@model IEnumerable<RegistroEventos.Models.Capitulo>

@{
    ViewData["Title"] = "Lista-Capitulos";
}
<link rel="stylesheet" href="~/css/Style-vistas.css" />


<div class="panel-izquierdo">
	<img id="logo-principal" src="img/fihnec-logo.png" >
    
</div>

<div>
    <a type="button" class="btn btn-outline-dark boton-panel" asp-action="Create" >Agregar</a>
    <a class="btn btn-outline-dark boton-inicio" asp-area="" asp-controller="Home" asp-action="Index">Menú</a>
    <a class="btn btn-outline-dark boton-inferior"asp-area="" asp-controller="Tipo_capitulo" asp-action="Index">Tipo de capítulos</a>
</div>


    <h4 class="txt-h4">Lista de Capítulos</h4>

<table class="table table-hover tabla-datos">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nombre_capitulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lugar_capitulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo_capitulo.nombre_tipo_capitulo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre_capitulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lugar_capitulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo_capitulo.nombre_tipo_capitulo)
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-outline-dark btn-action" asp-route-id="@item.id_capitulo">Editar</a> 
                <a asp-action="Details" class="btn btn-outline-dark btn-action" asp-route-id="@item.id_capitulo">Detalles</a> 
                <a asp-action="Delete" class="btn btn-outline-dark btn-action" asp-route-id="@item.id_capitulo">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>